### ISSUE TITLE
Feature request - monitor multiple harvesters

### ISSUE THREAD

**Issue by t0l0** [retzkek/chia_exporter#11]
Dear @retzkek ,
thanks for putting together your docker-compose stack chiamon which includes this chia_exporter.

I am currently evaluating this setup which looks promising, but if I am not mistaken, there is no option yet to monitor multiple (n) harvesters.

Any plans to do so in the near future?

Thanks,
Tobias

**Comment by retzkek** [comment]
You _can_ monitor multiple harvesters, you'd need to install chia_exporter, node_exporter, and promtail (if using) on each one, then configure prometheus and loki to scrape them.
