### ISSUE TITLE
netspace overflow and sync status gone

### ISSUE THREAD

**Issue by kevinkk525** [retzkek/chia_exporter#2]
(Sadly) the chia netspace has gone up a lot the last 12 hours and now doesn't fit into int64 anymore:

```
2021/05/22 04:51:25 error decoding get_blockchain_state response: json: cannot unmarshal number 9566905519282954240 into Go struct field .blockchain_state.Space of type int64
```

Also the blockchain_sync_status doesn't get populated but I don't see any error in the exporter log lines..

**Comment by retzkek** [comment]
Yeah sorry silly mistake, already fixed in [0.4.1](https://github.com/retzkek/chia_exporter/commit/6a3e947e04d0348896f86a750fafd3ff11393a5b).

**Comment by kevinkk525** [comment]
Ah thanks. Sorry I forgot to check the last commit on this repo, only checked the chiamon repo.. silly mistake on my side too :D
Thanks.

**Comment by retzkek** [comment]
No worries. Oh, and sync status also broke since all the blockchain metrics come from one API call, so when unmarshaling that response failed all those metrics were lost.
